# For more information: https://laravel.com/docs/sail
version: '3'
services:
    web:
        build: ./
        container_name: web
        ports:
            - '${APP_PORT:-8888}:80'
        env_file: .env
        tty: true
        volumes:
            - './src:/var/www/html'
            - './config/000-default.conf:/etc/apache2/sites-available/000-default.conf'
            - './config/php.ini-production:/usr/local/etc/php/php.ini-production'
            - './cron/root:/var/spool/cron/crontabs/root'
        networks:
            - web
        depends_on:
            - db
    db:
        image: 'postgres:latest'
        container_name: db
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        env_file: .env
        environment:
            POSTGRES_USER: '${POSTGRES_USER}'
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
        volumes:
            - './db:/var/lib/postgresql/data'
            - ./init/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
        networks:
            - web
networks:
    web:
        driver: bridge